# Generated by Django 2.2.6 on 2019-11-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EchoAnalyzer', '0003_auto_20191115_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='log',
            field=models.TextField(null=True),
        ),
    ]
