# Generated by Django 3.0 on 2019-12-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EchoAnalyzer', '0005_auto_20191116_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='processed_at',
            new_name='finished_processing_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='log',
        ),
        migrations.AddField(
            model_name='file',
            name='dicom_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
