# Generated by Django 3.0 on 2019-12-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EchoAnalyzer', '0006_auto_20191211_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='finished_processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='started_processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
