# Generated by Django 3.0 on 2019-12-31 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EchoAnalyzer', '0008_auto_20191231_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='processing_time',
        ),
    ]
